--SQL file
INSERT INTO MEDICO_ENTITY (ID,APELLIDO,ESPECIALIDAD,NOMBRE,REGISTRO_MEDICO) VALUES (03,'RAS','DEDO','RES','1234T');
INSERT INTO MEDICO_ENTITY (ID,APELLIDO,ESPECIALIDAD,NOMBRE,REGISTRO_MEDICO) VALUES (02,'PARDO','PIERNA','SANTI','NJF2566S');
INSERT INTO MEDICO_ENTITY (ID,APELLIDO,ESPECIALIDAD,NOMBRE,REGISTRO_MEDICO) VALUES (01,'FORERO','BARRIGA','CESAR','NJF566S');